Repository sul-dlss/argo, pull requests merged in 2019-08, with the labels that each got.

#1451 Merge virtual-merge in from dor-utils
  Gemfile.lock
  README.md
  bin/virtual-merge
Labels: SDR Fall 2019, Technical Debt, virtual merge

#1450 Extract ButtonsPresenter from the ArgoHelper
  app/controllers/bulk_jobs_controller.rb
  app/controllers/catalog_controller.rb
  app/helpers/argo_helper.rb
  app/presenters/buttons_presenter.rb
  app/views/catalog/_show_external_links.html.erb
  app/views/catalog/_show_sidebar.html.erb
  spec/helpers/argo_helper_spec.rb
  spec/presenters/buttons_presenter_spec.rb
  spec/views/catalog/_show_sidebar.html.erb_spec.rb
Labels: Technical Debt

#1462 Add virtual merge job
  Gemfile
  Gemfile.lock
  app/jobs/virtual_merge_job.rb
  bin/virtual-merge
  spec/jobs/virtual_merge_job_spec.rb
Labels: SDR Fall 2019, virtual merge

#1505 Move all version-related functionality to a new service class
  .rubocop_todo.yml
  app/controllers/versions_controller.rb
  app/jobs/close_version_job.rb
  app/jobs/generic_job.rb
  app/jobs/manage_catkey_job.rb
  app/jobs/prepare_job.rb
  app/jobs/virtual_merge_job.rb
  app/services/apply_mods_metadata.rb
  app/services/version_service.rb
  spec/features/item_view_metadata_spec.rb
  spec/jobs/manage_catkey_job_spec.rb
  spec/jobs/prepare_job_spec.rb
  spec/services/apply_mods_metadata_spec.rb
  spec/services/version_service_spec.rb
Labels: SDR Fall 2019, tech debt

#1528 Increased the number of collections returned in query
  app/models/concerns/permitted_queries.rb
Labels: SDR Fall 2019

#1527 [Needs PO approval] Tweak to Prepare objects bulk action form.
  app/views/bulk_actions/forms/_prepare_form.html.erb
Labels: SDR Fall 2019

#1524 [Needs PO approval] Changed label for description field on new bulk action form.
  app/views/bulk_actions/_form.html.erb
Labels: SDR Fall 2019
