Repository sul-dlss/argo, pull requests merged in 2019-09, with the labels that each got.

#1544 Do not call #version_object with arguments
  app/services/apply_mods_metadata.rb
  spec/services/apply_mods_metadata_spec.rb
Labels: bug

#1573 Improve refresh metadata err handling
  .gitignore
  .rubocop_todo.yml
  app/controllers/items_controller.rb
  spec/controllers/items_controller_spec.rb
Labels: SDR Fall 2019, descMd problems

#1520 [Needs PO review] Add missing permissions checks to background jobs
  .rubocop_todo.yml
  app/controllers/bulk_actions_controller.rb
  app/controllers/uploads_controller.rb
  app/jobs/close_version_job.rb
  app/jobs/generic_job.rb
  app/jobs/manage_catkey_job.rb
  app/jobs/modsulator_job.rb
  app/jobs/prepare_job.rb
  app/jobs/release_object_job.rb
  app/jobs/virtual_merge_job.rb
  app/models/ability.rb
  app/services/apply_mods_metadata.rb
  spec/controllers/uploads_controller_spec.rb
  spec/jobs/close_version_job_spec.rb
  spec/jobs/generic_job_spec.rb
  spec/jobs/manage_catkey_job_spec.rb
  spec/jobs/modsulator_job_spec.rb
  spec/jobs/prepare_job_spec.rb
  spec/jobs/release_object_job_spec.rb
  spec/jobs/virtual_merge_job_spec.rb
  spec/services/apply_mods_metadata_spec.rb
Labels: SDR Fall 2019, tech debt

#1473 [Needs PO approval] Add dropdown to set a status for an errored workflow item (design needed - blocker)
  app/controllers/workflows_controller.rb
  app/presenters/workflow_process_presenter.rb
  app/views/workflows/_show.html.erb
  spec/controllers/workflows_controller_spec.rb
  spec/models/ability_spec.rb
  spec/presenters/workflow_process_presenter_spec.rb
  spec/views/workflows/_show.html.erb_spec.rb
Labels: SDR Fall 2019, design needed

#1609 Convert inline script to a Stimulus controller
  Gemfile
  Gemfile.lock
  app/assets/javascripts/argo.js
  app/assets/javascripts/controllers/workflow_grid_controller.es6
  app/assets/stylesheets/argo/throbber.scss
  app/components/throbber.html.erb
  app/components/throbber.rb
  app/views/report/_workflow_grid.html.erb
  app/views/report/workflow_grid.html.erb
  config/application.rb
  spec/views/report/workflow_grid_spec.erb_spec.rb
Labels: SDR Fall 2019, tech debt

#1610 Use rails built in parameter validation
  app/controllers/report_controller.rb
  spec/controllers/report_controller_spec.rb
Labels: SDR Fall 2019, tech debt

#1614 Switch to the new workflow client update_status method
  Gemfile
  Gemfile.lock
  app/controllers/items_controller.rb
  app/controllers/report_controller.rb
  app/controllers/workflows_controller.rb
  spec/controllers/report_controller_spec.rb
  spec/controllers/workflows_controller_spec.rb
Labels: tech debt

#1603 new bulk action for checksum reporting
  .rubocop_todo.yml
  app/helpers/bulk_action_helper.rb
  app/jobs/checksum_report_job.rb
  app/models/bulk_action.rb
  app/views/bulk_actions/_checksum_report_job.html.erb
  app/views/bulk_actions/new.html.erb
  config/settings.yml
  spec/helpers/bulk_action_helper_spec.rb
  spec/jobs/checksum_report_job_spec.rb
Labels: SDR Fall 2019, checksum report

#1660 Avoid looking in solr for workflow templates
  Gemfile
  Gemfile.lock
  app/controllers/workflow_service_controller.rb
  app/helpers/apo_helper.rb
  spec/features/workflow_service_creation_spec.rb
Labels: tech debt

#1664 convert ChecksumReportJob to use preservation-client gem
  .rubocop_todo.yml
  app/jobs/checksum_report_job.rb
  spec/jobs/checksum_report_job_spec.rb
Labels: checksum report, tech debt
