Repository sul-dlss/argo, pull requests merged in 2022-06, with the labels that each got.

#3724 Add facet configuration for released to searchworks/earthworks
  app/controllers/catalog_controller.rb
  app/models/solr_document.rb
  config/locales/blacklight.en.yml
Labels: hold for PO review, SDR improvements

#3742 hardcode list of workflow options per issue #3741
  app/helpers/apo_helper.rb
Labels: hold for PO review

#3653 Registration form redesign
  app/controllers/dor/objects_controller.rb
  app/controllers/registrations_controller.rb
  app/forms/registration_form.rb
  app/javascript/argo.js
  app/javascript/controllers/index.js
  app/javascript/controllers/registration_controller.js
  app/javascript/controllers/registration_items_controller.js
  app/javascript/registration/grid.js
  app/javascript/registration/register.js
  app/views/apo/registration_options.html.erb
  app/views/registrations/_item_row.html.erb
  app/views/registrations/create_status.html.erb
  app/views/registrations/show.html.erb
  config/routes.rb
  spec/features/item_registration_spec.rb
  spec/forms/registration_form_spec.rb
  spec/requests/create_new_item_spec.rb
  spec/requests/registration_spec.rb
Labels: hold for PO review

#3684 Registration form csv
  app/controllers/registrations_controller.rb
  app/forms/csv_registration_form.rb
  app/javascript/controllers/index.js
  app/javascript/controllers/registration_tabs_controller.js
  app/jobs/register_druids_job.rb
  app/services/csv_upload_validator.rb
  app/services/registration_csv_converter.rb
  app/views/registrations/_item_row.html.erb
  app/views/registrations/show.html.erb
  config/routes.rb
  spec/features/item_registration_csv_spec.rb
  spec/fixtures/files/item_registration.csv
  spec/jobs/register_druids_job_spec.rb
  spec/requests/bulk_actions/import_structural_job_spec.rb
  spec/services/csv_upload_validator_spec.rb
  spec/services/registration_csv_converter_spec.rb
Labels: hold for PO review, SDR migration carryover

#3747 do not close objects when updating desc metadata if they are registered but not accessioned
  app/jobs/descriptive_metadata_import_job.rb
  spec/jobs/descriptive_metadata_import_job_spec.rb
Labels: hold for PO review

#3739 Group exported descriptions in downloadable cocina spreadsheet
  .rubocop.yml
  .rubocop_todo.yml
  app/jobs/descriptive_metadata_export_job.rb
  app/services/descriptions_grouper.rb
  app/services/forms_grouper.rb
  app/services/notes_grouper.rb
  spec/jobs/descriptive_metadata_export_job_spec.rb
  spec/services/descriptions_grouper_spec.rb
Labels: hold for PO review, martin wong

#3752 Validate barcode on registration page
  app/forms/registration_form.rb
  app/javascript/controllers/registration_controller.js
  app/views/registrations/_item_row.html.erb
  spec/features/item_registration_spec.rb
Labels: hold for PO review
